module HangmanArt
    def display_hangman(guesses)
        case
        when guesses == 5
            puts "___________.._______"
            puts "| .__________))______|"
            puts "| | / /     "
            puts "| |/ /      "
            puts "| | /       "
            puts "| |/        "
            puts "| |         "
            puts "| |         "
            puts "| |         "
            puts "| |            "
            puts "| |              "
            puts "| |              "
            puts "| |                "
            puts "| |         "
            puts "| |         "
            puts "| |         "
            puts "| |         "
            puts "| |         "
            puts "| |         "
            puts "'''''''''''|''''''''''|'|"
            puts "|'|''''''''|''''''''''|'|"
            puts "| |                   | |"
            puts ": :                   : :"
            puts ": :                   : :"
        when guesses == 4
            puts "___________.._______"
            puts "| .__________))______|"
            puts "| | / /      ||"
            puts "| |/ /       ||"
            puts "| | /        ||.-''."
            puts "| |/         |/  _  \\ "
            puts "| |          ||  `/,|"
            puts "| |          (\\\\`_.'"
            puts "| |         .-`--'."
            puts "| |            "
            puts "| |              "
            puts "| |              "
            puts "| |                "
            puts "| |         "
            puts "| |         "
            puts "| |         "
            puts "| |         "
            puts "| |         "
            puts "| |         "
            puts "'''''''''''|''''''''''|'|"
            puts "|'|''''''''|''''''''''|'|"
            puts "| |                   | |"
            puts ": :                   : :"
            puts ": :                   : :"
        when guesses == 3
            puts "___________.._______"
            puts "| .__________))______|"
            puts "| | / /      ||"
            puts "| |/ /       ||"
            puts "| | /        ||.-''."
            puts "| |/         |/  _  \\ "
            puts "| |          ||  `/,|"
            puts "| |          (\\\\`_.'"
            puts "| |         .-`--'."
            puts "| |         Y . . Y"
            puts "| |          |   | "
            puts "| |          | . |  "
            puts "| |          |   |   "
            puts "| |         "
            puts "| |         "
            puts "| |         "
            puts "| |         "
            puts "| |         "
            puts "| |         "
            puts "'''''''''''|''''''''''|'|"
            puts "|'|''''''''|''''''''''|'|"
            puts "| |                   | |"
            puts ": :                   : :"
            puts ": :                   : :"
        when guesses == 2
            puts "___________.._______"
            puts "| .__________))______|"
            puts "| | / /      ||"
            puts "| |/ /       ||"
            puts "| | /        ||.-''."
            puts "| |/         |/  _  \\ "
            puts "| |          ||  `/,|"
            puts "| |          (\\\\`_.'"
            puts "| |         .-`--'."
            puts "| |        /Y . . Y"
            puts "| |       // |   | "
            puts "| |      //  | . |  "
            puts "| |     ')   |   |   "
            puts "| |         "
            puts "| |         "
            puts "| |         "
            puts "| |         "
            puts "| |         "
            puts "| |         "
            puts "'''''''''''|''''''''''|'|"
            puts "|'|''''''''|''''''''''|'|"
            puts "| |                   | |"
            puts ": :                   : :"
            puts ": :                   : :"
        when guesses == 1
            puts "___________.._______"
            puts "| .__________))______|"
            puts "| | / /      ||"
            puts "| |/ /       ||"
            puts "| | /        ||.-''."
            puts "| |/         |/  _  \\ "
            puts "| |          ||  `/,|"
            puts "| |          (\\\\`_.'"
            puts "| |         .-`--'."
            puts "| |        /Y . . Y\\\\"
            puts "| |       // |   | \\\\"
            puts "| |      //  | . |  \\\\"
            puts "| |     ')   |   |   (`"
            puts "| |         "
            puts "| |         "
            puts "| |         "
            puts "| |         "
            puts "| |         "
            puts "| |         "
            puts "'''''''''''|''''''''''|'|"
            puts "|'|''''''''|''''''''''|'|"
            puts "| |                   | |"
            puts ": :                   : :"
            puts ": :                   : :"
        when guesses == 0
            puts "___________.._______"
            puts "| .__________))______|"
            puts "| | / /      ||"
            puts "| |/ /       ||"
            puts "| | /        ||.-''."
            puts "| |/         |/  _  \\ "
            puts "| |          ||  `/,|"
            puts "| |          (\\\\`_.'"
            puts "| |         .-`--'."
            puts "| |        /Y . . Y\\\\"
            puts "| |       // |   | \\\\"
            puts "| |      //  | . |  \\\\"
            puts "| |     ')   |   |   (`"
            puts "| |          ||'||"
            puts "| |          || ||"
            puts "| |          || ||"
            puts "| |          || ||"
            puts "| |         / | | \\"
            puts "| |         `-' `-'"
            puts "'''''''''''|_        |''|"
            puts "|'|'''''''\\ \\       ''|'|"
            puts "| |        \\ \\        | |"
            puts ": :         \\ \\       : :"
            puts ": :                   : :"
        end
    end
end